name: Build

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Disable userns security on latest ubuntu
      run: sudo sysctl kernel.apparmor_restrict_unprivileged_userns=0

    - name: Install bwrap
      run: sudo apt install bubblewrap

    - name: Run build all
      run: ./build_all.sh
